import { NotFoundException } from '@nestjs/common';
import { DataSource } from 'typeorm';
import { StatsService, timeSeriesTimestampSql, hourBucketSql, maxCreatedAtSql } from './stats.service';
import { Session, SessionStatus } from '../session/entities/session.entity';
import { Message, MessageDirection, MessageStatus } from '../message/entities/message.entity';

// these two analytics queries used SQLite-only strftime(), which 500s on a Postgres
// data DB. The dialect-correct SQL is generated by these pure helpers; the Postgres branch is
// unit-tested here (a live Postgres isn't available in CI), and the SQLite path is exercised
// end-to-end below so the fix can't regress the working backend.
describe('stats SQL dialect helpers', () => {
  it('uses strftime on sqlite (hour + day buckets)', () => {
    expect(timeSeriesTimestampSql('sqlite', 'hour')).toBe(`strftime('%Y-%m-%d %H:00:00', m.createdAt)`);
    expect(timeSeriesTimestampSql('sqlite', 'day')).toBe(`strftime('%Y-%m-%d', m.createdAt)`);
    expect(hourBucketSql('sqlite')).toBe(`CAST(strftime('%H', m.createdAt) AS INTEGER)`);
  });

  it('uses to_char/extract with a quoted createdAt on postgres', () => {
    expect(timeSeriesTimestampSql('postgres', 'hour')).toBe(`to_char(m."createdAt", 'YYYY-MM-DD HH24:00:00')`);
    expect(timeSeriesTimestampSql('postgres', 'day')).toBe(`to_char(m."createdAt", 'YYYY-MM-DD')`);
    expect(hourBucketSql('postgres')).toBe(`CAST(EXTRACT(HOUR FROM m."createdAt") AS INTEGER)`);
  });

  it('formats MAX(createdAt) to an identical text timestamp on both engines (lastActive parity)', () => {
    // Postgres returns a timestamp the driver hydrates to a JS Date (serialized to a different ISO
    // string than SQLite's stored text); pinning both to the same to_char/strftime format keeps the
    // lastActive field stable regardless of the backing database.
    expect(maxCreatedAtSql('sqlite')).toBe(`strftime('%Y-%m-%d %H:%M:%S', MAX(m.createdAt))`);
    expect(maxCreatedAtSql('postgres')).toBe(`to_char(MAX(m."createdAt"), 'YYYY-MM-DD HH24:MI:SS')`);
  });
});

describe('StatsService time-series + hourly activity on SQLite (end-to-end regression)', () => {
  let ds: DataSource;
  let service: StatsService;

  beforeEach(async () => {
    ds = new DataSource({
      type: 'better-sqlite3',
      database: ':memory:',
      entities: [Session, Message],
      synchronize: true,
    });
    await ds.initialize();
    const cache = { setSessionsStats: jest.fn() };
    const config = { get: () => 30000 };
    service = new StatsService(ds.getRepository(Session), ds.getRepository(Message), cache as never, config as never);
  });

  afterEach(async () => {
    await ds.destroy();
  });

  const seedMessage = (over: Partial<Message>) =>
    ds.getRepository(Message).save(
      ds.getRepository(Message).create({
        sessionId: 's1',
        chatId: 'c1',
        from: 'a',
        to: 'b',
        type: 'text',
        direction: MessageDirection.OUTGOING,
        status: MessageStatus.SENT,
        ...over,
      }),
    );

  it('getMessageStats returns a populated time series without throwing', async () => {
    await ds
      .getRepository(Session)
      .save(ds.getRepository(Session).create({ id: 's1', name: 'n', status: SessionStatus.READY, config: {} }));
    await seedMessage({ direction: MessageDirection.OUTGOING });
    await seedMessage({ direction: MessageDirection.INCOMING });

    const stats = await service.getMessageStats('24h');
    expect(Array.isArray(stats.timeSeries)).toBe(true);
    expect(stats.timeSeries.length).toBeGreaterThanOrEqual(1);
    const totals = stats.timeSeries.reduce(
      (acc, p) => ({ sent: acc.sent + p.sent, received: acc.received + p.received }),
      {
        sent: 0,
        received: 0,
      },
    );
    expect(totals.sent).toBe(1);
    expect(totals.received).toBe(1);
    // The hour bucket must be the zero-padded chronological label strftime produces.
    expect(stats.timeSeries[0].timestamp).toMatch(/^\d{4}-\d{2}-\d{2} \d{2}:00:00$/);
  });

  it('getMessageStatsForRange uses an exact half-open window for repeatable exports', async () => {
    await ds
      .getRepository(Session)
      .save(ds.getRepository(Session).create({ id: 's1', name: 'n', status: SessionStatus.READY, config: {} }));

    const since = new Date('2026-02-01T00:00:00.000Z');
    const until = new Date('2026-03-03T00:00:00.000Z');
    await seedMessage({ createdAt: new Date('2026-01-31T23:59:59.999Z'), body: 'before' });
    await seedMessage({ createdAt: since, body: 'start included' });
    await seedMessage({ createdAt: new Date('2026-03-02T23:59:59.999Z'), body: 'end included' });
    await seedMessage({ createdAt: until, body: 'next window' });

    const stats = await service.getMessageStatsForRange(since, until);

    expect(stats.summary.sent).toBe(2);
    expect(stats.timeSeries.reduce((total, point) => total + point.sent, 0)).toBe(2);
    expect(stats.byType).toEqual({ text: 2 });
    expect(stats.topChats[0].messageCount).toBe(2);
  });

  it('getMessageStatsForRange rejects an invalid or empty window', async () => {
    const boundary = new Date('2026-09-01T00:00:00.000Z');
    await expect(service.getMessageStatsForRange(boundary, boundary)).rejects.toThrow(RangeError);
    await expect(service.getMessageStatsForRange(new Date('invalid'), boundary)).rejects.toThrow(RangeError);
  });

  it('returns sent, received, and distinct-chat interaction analytics for the period', async () => {
    await ds
      .getRepository(Session)
      .save(ds.getRepository(Session).create({ id: 's1', name: 'n', status: SessionStatus.READY, config: {} }));
    await ds
      .getRepository(Session)
      .save(ds.getRepository(Session).create({ id: 's2', name: 'n2', status: SessionStatus.READY, config: {} }));
    await seedMessage({
      chatId: 'alice@c.us',
      direction: MessageDirection.OUTGOING,
      status: MessageStatus.READ,
      deliveryCount: 1,
      readCount: 1,
      deliveredTo: ['alice@c.us'],
      readBy: ['alice@c.us'],
      reactionCount: 2,
    });
    await seedMessage({
      chatId: 'alice@c.us',
      direction: MessageDirection.OUTGOING,
      status: MessageStatus.DELIVERED,
      deliveryCount: 1,
      deliveredTo: ['alice@c.us'],
    });
    await seedMessage({ chatId: 'bob@c.us', direction: MessageDirection.INCOMING, status: MessageStatus.READ });
    await seedMessage({
      sessionId: 's2',
      chatId: 'alice@c.us',
      direction: MessageDirection.INCOMING,
      status: MessageStatus.READ,
    });

    const stats = await service.getMessageStats('24h');

    expect(stats.summary).toEqual({
      sent: 2,
      received: 2,
      interactions: 3,
      deliveredRecipients: 1,
      readRecipients: 1,
      reactedMessages: 1,
      emojiReactions: 2,
    });
  });

  it('filters every message metric to multiple groups while retaining the all-group breakdown', async () => {
    await ds
      .getRepository(Session)
      .save(ds.getRepository(Session).create({ id: 's1', name: 'primary', status: SessionStatus.READY, config: {} }));
    await ds
      .getRepository(Session)
      .save(ds.getRepository(Session).create({ id: 's2', name: 'secondary', status: SessionStatus.READY, config: {} }));

    await seedMessage({
      chatId: 'alpha@g.us',
      chatName: 'Alpha Team',
      body: 'hello',
      direction: MessageDirection.OUTGOING,
      deliveryCount: 4,
      readCount: 3,
      deliveredTo: ['a@c.us', 'b@c.us', 'c@c.us', 'd@c.us'],
      readBy: ['a@c.us', 'b@c.us', 'c@c.us'],
      reactionCount: 3,
    });
    await seedMessage({
      chatId: 'alpha@g.us',
      chatName: 'Alpha Team',
      type: 'image',
      body: '',
      metadata: { media: { mimetype: 'image/png' } },
      direction: MessageDirection.INCOMING,
    });
    await seedMessage({
      sessionId: 's2',
      chatId: 'alpha@g.us',
      chatName: 'Alpha Team',
      body: 'second session',
      direction: MessageDirection.OUTGOING,
      deliveryCount: 5,
      readCount: 2,
      deliveredTo: ['a@c.us', 'b@c.us', 'f@c.us', 'g@c.us'],
      readBy: ['a@c.us', 'e@c.us'],
      reactionCount: 1,
    });
    await seedMessage({
      chatId: 'beta@g.us',
      chatName: 'Beta Team',
      body: 'another group',
      direction: MessageDirection.OUTGOING,
      deliveryCount: 2,
      readCount: 1,
      // This member also appears in Alpha. The headline must add the per-group audiences rather
      // than deduplicating the same person across different groups.
      deliveredTo: ['a@c.us', 'i@c.us'],
      readBy: ['a@c.us'],
    });
    await seedMessage({
      chatId: 'gamma@g.us',
      chatName: 'Gamma Team',
      body: 'not selected',
      direction: MessageDirection.OUTGOING,
      deliveryCount: 1,
      readCount: 1,
      deliveredTo: ['j@c.us'],
      readBy: ['j@c.us'],
    });
    await seedMessage({
      chatId: 'gamma@g.us',
      chatName: 'Gamma Team',
      body: 'also not selected',
      direction: MessageDirection.OUTGOING,
      deliveryCount: 1,
      deliveredTo: ['j@c.us'],
    });
    await seedMessage({
      chatId: 'person@c.us',
      chatName: 'Direct contact',
      body: 'private',
      direction: MessageDirection.INCOMING,
    });

    const stats = await service.getMessageStats('24h', ['alpha@g.us', 'beta@g.us', 'alpha@g.us']);

    expect(stats.summary).toEqual({
      sent: 3,
      received: 1,
      interactions: 3,
      deliveredRecipients: 9,
      readRecipients: 5,
      reactedMessages: 2,
      emojiReactions: 4,
    });
    expect(stats.timeSeries.reduce((total, point) => total + point.sent + point.received, 0)).toBe(4);
    expect(stats.byType).toEqual({ text: 3, image: 1 });
    expect(stats.byTypeBreakdown).toEqual([
      { type: 'text', sent: 3, received: 0, total: 3, deliveredRecipients: 9, readRecipients: 5 },
      { type: 'image', sent: 0, received: 1, total: 1, deliveredRecipients: 0, readRecipients: 0 },
    ]);
    expect(stats.bySession).toEqual(
      expect.arrayContaining([
        { sessionId: 's1', name: 'primary', sent: 2, received: 1 },
        { sessionId: 's2', name: 'secondary', sent: 1, received: 0 },
      ]),
    );
    expect(stats.topChats).toHaveLength(2);
    expect(stats.topChats).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          chatId: 'alpha@g.us',
          chatName: 'Alpha Team',
          sent: 2,
          received: 1,
          messageCount: 3,
          deliveredRecipients: 7,
          readRecipients: 4,
        }),
        expect.objectContaining({
          chatId: 'beta@g.us',
          chatName: 'Beta Team',
          sent: 1,
          received: 0,
          messageCount: 1,
          deliveredRecipients: 2,
          readRecipients: 1,
        }),
      ]),
    );
    expect(stats.topChats[0].lastActive).toMatch(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/);
    expect(stats.groupBreakdown).toHaveLength(3);
    expect(stats.groupBreakdown).toEqual(
      expect.arrayContaining([
        {
          groupId: 'alpha@g.us',
          groupName: 'Alpha Team',
          sent: 2,
          received: 1,
          total: 3,
          deliveredRecipients: 7,
          readRecipients: 4,
        },
        {
          groupId: 'gamma@g.us',
          groupName: 'Gamma Team',
          sent: 2,
          received: 0,
          total: 2,
          deliveredRecipients: 1,
          readRecipients: 1,
        },
        {
          groupId: 'beta@g.us',
          groupName: 'Beta Team',
          sent: 1,
          received: 0,
          total: 1,
          deliveredRecipients: 2,
          readRecipients: 1,
        },
      ]),
    );
  });

  it('getMessageStats topChats surfaces chatName via the MAX aggregate (ignoring null rows)', async () => {
    await ds
      .getRepository(Session)
      .save(ds.getRepository(Session).create({ id: 's1', name: 'n', status: SessionStatus.READY, config: {} }));
    await seedMessage({ chatId: 'alice@c.us', chatName: 'Alice', direction: MessageDirection.INCOMING });
    await seedMessage({ chatId: 'alice@c.us', chatName: undefined, direction: MessageDirection.INCOMING });

    const stats = await service.getMessageStats('24h');
    const chat = stats.topChats.find(c => c.chatId === 'alice@c.us');
    // MAX(m.chatName) across the group returns the non-null name, so a legacy null row can't blank it.
    expect(chat?.chatName).toBe('Alice');
  });

  it('counts receipt audiences once per chat and message type', async () => {
    await ds
      .getRepository(Session)
      .save(ds.getRepository(Session).create({ id: 's1', name: 'n', status: SessionStatus.READY, config: {} }));
    await seedMessage({
      chatId: 'team-one@g.us',
      type: 'text',
      body: 'first text',
      deliveryCount: 2,
      readCount: 1,
      deliveredTo: ['a@c.us', 'b@c.us'],
      readBy: ['a@c.us'],
    });
    await seedMessage({
      chatId: 'team-one@g.us',
      type: 'text',
      body: 'second text',
      deliveryCount: 2,
      readCount: 1,
      deliveredTo: ['a@c.us', 'c@c.us'],
      readBy: ['b@c.us'],
    });
    await seedMessage({
      chatId: 'team-one@g.us',
      type: 'image',
      body: '',
      metadata: { media: { mimetype: 'image/png' } },
      deliveryCount: 1,
      readCount: 1,
      deliveredTo: ['a@c.us'],
      readBy: ['a@c.us'],
    });
    await seedMessage({
      chatId: 'team-two@g.us',
      type: 'image',
      body: '',
      metadata: { media: { mimetype: 'image/png' } },
      deliveryCount: 1,
      readCount: 1,
      deliveredTo: ['a@c.us'],
      readBy: ['a@c.us'],
    });

    const stats = await service.getMessageStats('24h');

    expect(stats.byTypeBreakdown).toEqual([
      { type: 'image', sent: 2, received: 0, total: 2, deliveredRecipients: 2, readRecipients: 2 },
      { type: 'text', sent: 2, received: 0, total: 2, deliveredRecipients: 3, readRecipients: 2 },
    ]);
    // The same reader can appear in each content type, while the headline remains deduplicated per chat.
    expect(stats.summary.deliveredRecipients).toBe(4);
    expect(stats.summary.readRecipients).toBe(3);
  });

  it('getMessageStats byType excludes content-less system/event rows (no body AND no metadata)', async () => {
    await ds
      .getRepository(Session)
      .save(ds.getRepository(Session).create({ id: 's1', name: 'n', status: SessionStatus.READY, config: {} }));
    await seedMessage({ body: 'hello' });
    // A media message with no caption (body '') but a metadata.media payload must still be counted —
    // only rows empty on BOTH are excluded.
    await seedMessage({ type: 'image', body: '', metadata: { media: { mimetype: 'image/png', data: 'x' } } });
    // The misleading slice: an @lid privacy-user event the engine maps to `unknown` — no content at all.
    await seedMessage({ type: 'unknown', body: '', direction: MessageDirection.INCOMING });

    const stats = await service.getMessageStats('24h');
    expect(stats.byType).toEqual({ text: 1, image: 1 });
    expect(stats.byTypeBreakdown).toEqual([
      { type: 'image', sent: 1, received: 0, total: 1, deliveredRecipients: 0, readRecipients: 0 },
      { type: 'text', sent: 1, received: 0, total: 1, deliveredRecipients: 0, readRecipients: 0 },
    ]);
  });

  it('time-series query never groups by the bare reserved word `timestamp` (Postgres-safe)', async () => {
    await ds
      .getRepository(Session)
      .save(ds.getRepository(Session).create({ id: 's1', name: 'n', status: SessionStatus.READY, config: {} }));
    await seedMessage({ direction: MessageDirection.OUTGOING });

    // SQLite tolerates `GROUP BY timestamp`, but `timestamp` is a reserved type keyword in Postgres
    // and crashes there ("column m.createdAt must appear in the GROUP BY"). Assert the generated SQL,
    // not the result, so the fix can't silently regress on the backend the test DB doesn't exercise.
    const captured: string[] = [];
    const repo = ds.getRepository(Message);
    const origCreate = repo.createQueryBuilder.bind(repo);
    jest.spyOn(repo, 'createQueryBuilder').mockImplementation((alias?: string) => {
      const qb = origCreate(alias);
      const origGetRawMany = qb.getRawMany.bind(qb);
      jest.spyOn(qb, 'getRawMany').mockImplementation((async () => {
        captured.push(qb.getQuery());
        return origGetRawMany();
      }) as never);
      return qb;
    });

    await service.getMessageStats('24h');

    expect(captured.some(sql => /GROUP BY/i.test(sql))).toBe(true); // sanity: a grouped query was built
    for (const sql of captured) {
      expect(sql).not.toMatch(/GROUP BY\s+timestamp\b/i);
    }
  });

  it('no analytics query groups/orders by a bare reserved word — on the Postgres dialect shape too', async () => {
    await ds
      .getRepository(Session)
      .save(ds.getRepository(Session).create({ id: 's1', name: 'n', status: SessionStatus.READY, config: {} }));
    await seedMessage({ direction: MessageDirection.OUTGOING });

    // Force the Postgres SQL shape and capture the generated SQL WITHOUT executing (SQLite can't run
    // to_char/EXTRACT). groupBy/orderBy arguments are emitted verbatim, so this sweeps every grouped
    // analytics query for a reserved-word alias on the dialect the SQLite test DB can't exercise —
    // the exact #476 blindness class, extended beyond the single time-series query.
    // Shadow the (prototype) getter on this fresh per-test instance so it can't leak to other tests.
    Object.defineProperty(service, 'dataDbType', { get: () => 'postgres', configurable: true });

    const captured: string[] = [];
    const repo = ds.getRepository(Message);
    const origCreate = repo.createQueryBuilder.bind(repo);
    jest.spyOn(repo, 'createQueryBuilder').mockImplementation((alias?: string) => {
      const qb = origCreate(alias);
      jest.spyOn(qb, 'getRawMany').mockImplementation(() => {
        captured.push(qb.getQuery());
        return Promise.resolve([]);
      });
      return qb;
    });

    await service.getMessageStats('24h'); // time-series (bucket) + byType + bySession + topChats
    await service.getSessionStats('s1'); // hourly activity (hour)

    expect(captured.length).toBeGreaterThan(0);
    // A small set of PostgreSQL reserved type/keywords that a naive alias could collide with.
    const PG_RESERVED = ['timestamp', 'user', 'order', 'end', 'all', 'column', 'table'];
    for (const sql of captured) {
      for (const kw of PG_RESERVED) {
        expect(sql).not.toMatch(new RegExp(`GROUP BY\\s+["']?${kw}["']?\\s*(,|$|\\s)`, 'i'));
        expect(sql).not.toMatch(new RegExp(`ORDER BY\\s+["']?${kw}["']?\\s*(,|$|\\s|ASC|DESC)`, 'i'));
      }
    }
  });

  it('no analytics query orders/groups by an unquoted mixed-case alias (Postgres case-folds it → 42703)', async () => {
    await ds
      .getRepository(Session)
      .save(ds.getRepository(Session).create({ id: 's1', name: 'n', status: SessionStatus.READY, config: {} }));
    await seedMessage({ direction: MessageDirection.OUTGOING });

    Object.defineProperty(service, 'dataDbType', { get: () => 'postgres', configurable: true });

    const captured: string[] = [];
    const repo = ds.getRepository(Message);
    const origCreate = repo.createQueryBuilder.bind(repo);
    jest.spyOn(repo, 'createQueryBuilder').mockImplementation((alias?: string) => {
      const qb = origCreate(alias);
      jest.spyOn(qb, 'getRawMany').mockImplementation(() => {
        captured.push(qb.getQuery());
        return Promise.resolve([]);
      });
      return qb;
    });

    await service.getMessageStats('24h'); // time-series + byType + bySession + topChats
    await service.getSessionStats('s1');

    expect(captured.length).toBeGreaterThan(0);
    // Postgres folds an UNQUOTED identifier to lowercase; a mixed-case alias defined with quotes
    // (COUNT(*) AS "messageCount") then no longer matches a bare `ORDER BY messageCount` → it looks for
    // "messagecount" and 42703s. SQLite is case-insensitive so it never surfaced. Flag any bare
    // (unquoted) ORDER BY / GROUP BY term that contains an uppercase letter.
    const offenders: string[] = [];
    for (const sql of captured) {
      for (const clause of sql.match(/\b(?:ORDER|GROUP) BY\s+[^\s,]+/gi) ?? []) {
        const term = clause.replace(/\b(?:ORDER|GROUP) BY\s+/i, '');
        // Only a BARE identifier (no quotes, no dots, no parens) folds — `COUNT(*)`, `to_char(...)`,
        // `"m"."chatId"` are all safe; `messageCount` is the landmine.
        if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(term) && /[A-Z]/.test(term)) offenders.push(`${clause}  ::  ${sql}`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it('getSessionStats returns 24 hourly buckets with the right counts', async () => {
    await ds
      .getRepository(Session)
      .save(ds.getRepository(Session).create({ id: 's1', name: 'n', status: SessionStatus.READY, config: {} }));
    await seedMessage({ direction: MessageDirection.OUTGOING });
    await seedMessage({ direction: MessageDirection.OUTGOING });
    await seedMessage({ direction: MessageDirection.INCOMING });

    const stats = await service.getSessionStats('s1');
    expect(stats.hourlyActivity).toHaveLength(24);
    const totals = stats.hourlyActivity.reduce(
      (acc, h) => ({ sent: acc.sent + h.sent, received: acc.received + h.received }),
      { sent: 0, received: 0 },
    );
    expect(totals.sent).toBe(2);
    expect(totals.received).toBe(1);
  });
});

describe('StatsService aggregate memo (in-process TTL)', () => {
  let ds: DataSource;

  beforeEach(async () => {
    ds = new DataSource({
      type: 'better-sqlite3',
      database: ':memory:',
      entities: [Session, Message],
      synchronize: true,
    });
    await ds.initialize();
    const sessions = ds.getRepository(Session);
    await sessions.save(sessions.create({ id: 's1', name: 'n1', status: SessionStatus.READY, config: {} }));
    await sessions.save(sessions.create({ id: 's2', name: 'n2', status: SessionStatus.READY, config: {} }));
    const messages = ds.getRepository(Message);
    const base = {
      chatId: 'c1',
      from: 'a',
      to: 'b',
      type: 'text',
      direction: MessageDirection.OUTGOING,
      status: MessageStatus.SENT,
    };
    await messages.save(messages.create({ ...base, sessionId: 's1' }));
    await messages.save(messages.create({ ...base, sessionId: 's2' }));
  });

  afterEach(async () => {
    await ds.destroy();
  });

  const makeService = (ttlMs: number) =>
    new StatsService(
      ds.getRepository(Session),
      ds.getRepository(Message),
      { setSessionsStats: jest.fn() } as never,
      { get: () => ttlMs } as never,
    );

  it('serves a repeated identical call from the memo within the TTL (no second DB hit)', async () => {
    const service = makeService(30000);
    const spy = jest.spyOn(ds.getRepository(Message), 'createQueryBuilder');

    await service.getMessageStats('24h');
    const afterFirst = spy.mock.calls.length;
    expect(afterFirst).toBeGreaterThan(0);

    await service.getMessageStats('24h');
    expect(spy.mock.calls.length).toBe(afterFirst);
  });

  it('re-runs the aggregate once the TTL has expired', async () => {
    const service = makeService(30000);
    const spy = jest.spyOn(ds.getRepository(Message), 'createQueryBuilder');
    const nowSpy = jest.spyOn(Date, 'now').mockReturnValue(1_000_000);
    try {
      await service.getMessageStats('24h');
      const afterFirst = spy.mock.calls.length;

      nowSpy.mockReturnValue(1_000_000 + 30_001);
      await service.getMessageStats('24h');
      expect(spy.mock.calls.length).toBeGreaterThan(afterFirst);
    } finally {
      nowSpy.mockRestore();
    }
  });

  it('keys the memo by query shape and by session id', async () => {
    const service = makeService(30000);
    const spy = jest.spyOn(ds.getRepository(Message), 'createQueryBuilder');

    await service.getMessageStats('24h');
    let n = spy.mock.calls.length;
    await service.getMessageStats('7d'); // different period → different key → DB hit
    expect(spy.mock.calls.length).toBeGreaterThan(n);

    n = spy.mock.calls.length;
    await service.getSessionStats('s1');
    await service.getSessionStats('s1'); // memo hit — no new queries
    const afterS1 = spy.mock.calls.length;
    expect(afterS1).toBeGreaterThan(n);

    await service.getSessionStats('s2'); // different session → different key → DB hit
    expect(spy.mock.calls.length).toBeGreaterThan(afterS1);
  });

  it('a 0 TTL disables the memo (every call hits the DB)', async () => {
    const service = makeService(0);
    const spy = jest.spyOn(ds.getRepository(Message), 'createQueryBuilder');

    await service.getMessageStats('24h');
    const n = spy.mock.calls.length;
    await service.getMessageStats('24h');
    expect(spy.mock.calls.length).toBeGreaterThan(n);
  });

  it('does not serve a deleted session from the memo — the stale entry is evicted, not served', async () => {
    const service = makeService(30000);

    const first = await service.getSessionStats('s1'); // populates the 'session:s1' memo entry
    expect(first.session.name).toBe('n1');

    await ds.getRepository(Session).delete('s1');
    // Within the TTL the memo still holds the deleted session's snapshot; serving it would
    // resurrect a deleted session with a 200 instead of the honest 404.
    await expect(service.getSessionStats('s1')).rejects.toThrow(NotFoundException);

    // The stale entry is evicted, not just bypassed: a re-created session recomputes immediately
    // instead of waiting out the TTL with the pre-delete snapshot.
    await ds
      .getRepository(Session)
      .save(
        ds.getRepository(Session).create({ id: 's1', name: 'n1-recreated', status: SessionStatus.READY, config: {} }),
      );
    const recomputed = await service.getSessionStats('s1');
    expect(recomputed.session.name).toBe('n1-recreated');
  });

  it('bounds every cross-session aggregate with a createdAt range predicate the standalone index serves', async () => {
    const service = makeService(30000);
    // Capture the generated SQL the same way the reserved-word regression tests above do.
    const captured: string[] = [];
    const repo = ds.getRepository(Message);
    const origCreate = repo.createQueryBuilder.bind(repo);
    jest.spyOn(repo, 'createQueryBuilder').mockImplementation((alias?: string) => {
      const qb = origCreate(alias);
      const origGetRawMany = qb.getRawMany.bind(qb);
      jest.spyOn(qb, 'getRawMany').mockImplementation((async () => {
        captured.push(qb.getQuery());
        return origGetRawMany();
      }) as never);
      return qb;
    });

    await service.getMessageStats('24h'); // time-series + byType + bySession + topChats

    expect(captured.length).toBeGreaterThan(0);
    // IDX_messages_createdAt serves `createdAt >= ?`; an unbounded GROUP BY here would be the
    // full-history scan this service must no longer run.
    for (const sql of captured) {
      expect(sql).toMatch(/WHERE\s+.*"createdAt"\s*>=/i);
    }
  });
});
